//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_Recognition_AI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language_Recognition_AI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministar unutarnjih poslova Mohamed Ibrahim, koji je u septembru preživio pokušaj ubistva, naredio je policiji da se odlučno suprotstavi svakom pokušaju kršenja zakona, prenosi Mena.	bs
        ///Također, upriličen je i trilateralni sastanak ministara vanjskih poslova Bosne i Hercegovine, Republike Srbije i Republike Turske tokom kojeg je dr. Lagumdžija sa ministrima Ivanom Mrkićem i Ahmetom Davutoğluom razgovarao o trilateralnom sastanku na nivou ministara vanjskih poslova koji bi se trebao održati u Beogradu krajem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSL_DEV {
            get {
                return ResourceManager.GetString("DSL_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 57,5 miliona maloljetnih djevojčica prisilno stupi u brak širom svijeta, dok čak 40 odsto od tog broja čine maloljetne Indijke.	bs
        ///- Nakon ovih kalkulacija, ubrzo je postalo jasno da izuzetno velike zvijezde nisu nikakva misterija – kaže Sambaran.	bs
        ///U okviru programa Modul Memorije Internacionalnog teatarskog festivala MESS danas u 20 sati na sceni Sarajevskog ratnog teatra – SARTR bit će izvedena predstava DAH teatra „Prelazeći liniju“, u režiji Dijane Milošević.	bs
        ///Sagrađen je po istom principu kao i s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSL_TRAIN {
            get {
                return ResourceManager.GetString("DSL_TRAIN", resourceCulture);
            }
        }
    }
}
